services:
  mysql:
    image: mariadb:lts
    container_name: homelab_mysql
    restart: always
    environment:
      MARIADB_USER: admin
      MARIADB_PASSWORD_FILE: /run/secrets/mysql_admin_password
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/mysql_admin_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    secrets:
      - mysql_admin_password
    networks:
      - homelab

  cron:
    build:
      context: services/cron
    container_name: homelab_cron
    restart: unless-stopped
    secrets:
      - turso_api_token
      - dropbox_token

  nginx:
    build:
      context: services/nginx
    container_name: homelab_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    networks:
      - homelab

  website-museum:
    build:
      context: services/website-museum
    container_name: homelab_museum
    restart: unless-stopped
    ports:
      - "8001:80"
    volumes:
      - museum_data:/app/data
    networks:
      - homelab

  website-files:
    build:
      context: services/website-files
    container_name: homelab_files
    restart: unless-stopped
    ports:
      - "8002:80"
    volumes:
      - files_data:/app/data
    networks:
      - homelab

  website-land:
    build:
      context: services/website-land
    container_name: homelab_land
    restart: unless-stopped
    volumes:
      - land_data:/app/var
    ports:
      - "8003:80"
    networks:
      - homelab

networks:
  homelab:

volumes:
  mysql_data:
  museum_data:
  files_data:
  land_data:

secrets:
  mysql_admin_password:
    file: ./secrets/mysql_admin_password.txt
  turso_api_token:
    file: ./secrets/turso_api_token.txt
  dropbox_token:
    file: ./secrets/dropbox_token.txt
