services:
  mysql:
    image: mariadb:lts
    container_name: homelab_mysql
    restart: always
    environment:
      MARIADB_USER: admin
      MARIADB_PASSWORD_FILE: /run/secrets/mysql_admin_password
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/mysql_admin_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    secrets:
      - mysql_admin_password

  cron:
    build:
      context: services/cron
    container_name: homelab_cron
    restart: unless-stopped
    secrets:
      - turso_api_token
      - dropbox_token

  website-land:
    build:
      context: services/land-website
    container_name: homelab_land
    restart: unless-stopped
    ports:
      - "8001:8080"

volumes:
  mysql_data:

secrets:
  mysql_admin_password:
    file: ./secrets/mysql_admin_password.txt
  turso_api_token:
    file: ./secrets/turso_api_token.txt
  dropbox_token:
    file: ./secrets/dropbox_token.txt
